#!/bin/bash

echo "Type-checking svgpanel.py"
mypy --strict --module svgpanel || exit 1

echo "Type-checking unittest.py"
mypy --strict unittest.py || exit 1

rm -f output/*.svg
./unittest.py all || exit 1

for name in empty font01; do
    echo "runtests: checking ${name}.svg"
    if ! diff {correct,output}/${name}.svg; then
        echo "FAIL(runtests): incorrect output for ${name}.svg"
        exit 1
    fi
done

cat pass.txt
exit 0
