name: svgpanel unit tests
on: [push]
jobs:
  SvgPanelTests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Python packages
      run: python -m pip install --upgrade pip && pip install mypy fonttools
    - name: svgpanel tests
      run: cd src && ./runtests
